### ISSUE TITLE
Using a vec of rules

### ISSUE THREAD

**Issue by piedoom** [nshcat/lsystems-core#4]
Hey there! Sorry to open an issue on this project since it has been inactive, so I totally understand if this is not something you're interested in right now. I was running into an issue with the example, as the `rules` seems to expect just a string.  

```rs
lsystem.parse(                           // Set axiom and rewriting
     "A",                                // rules
     vec![ "A -> FAB", "B -> +F" ]
);
```

Error:
```
mismatched types
expected reference `&str`
      found struct `std::vec::Vec<&str>`
```
Has this changed since the README was written, maybe? (Maybe commas are used instead?)
Thanks!

**Comment by nshcat** [comment]
Hi,

Yes, unfortunately the API has changed while I was developing the companion visualization app lsystems-gui.

It expects a string of rules concatenated by a newline `\n`. I really should change that at some point :D

Cheers,
Katharina

**Comment by piedoom** [comment]
Perfect, thank you!
